version: '3'

services:
  caffeine_blues:
    container_name: caffeine_blues
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    networks:
      - caffeineBluesNetwork

networks:
  caffeineBluesNetwork:
